### ISSUE TITLE
Problem with WallabyJS

### ISSUE THREAD

**Issue by davidmoshal** [mzgoddard/hard-source-webpack-plugin#107]
Problem with WallabyJS:

```
A child compiler (html-webpack-plugin for "index.html") does not
have a memory cache. Enable a memory cache with webpack's
`cache` configuration option. HardSourceWebpackPlugin will be
disabled for this child compiler until then.

[at-loader] Using typescript@2.2.1 from typescript and "tsconfig.json" from <path-removed>/tsconfig.json.

Tue, 28 Feb 2017 02:06:19 GMT wallaby:project Error: ENOENT: no such file or directory, open '<path-removed>/cache/196e18401b67579637a91b58941ad614b3b1bdcb3c12a6cd5063f831ad665f03/stamp'
From previous event:
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
  at Object.postprocessor (/<path-removed>/Library/Caches/WebStorm2016.3/wallaby/wallaby/server.js:16:16202)
  at <path-removed>/Library/Caches/WebStorm2016.3/wallaby/wallaby/server.js:16:31466
  at Timeout._onTimeout (/<path-removed>/Library/Caches/WebStorm2016.3/wallaby/wallaby/server.js:16:31017)
  at ontimeout (timers.js:365:14)
  at tryOnTimeout (timers.js:237:5)
  at Timer.listOnTimeout (timers.js:207:5)
Tue, 28 Feb 2017 02:06:19 GMT wallaby:project Test run finished
Tue, 28 Feb 2017 02:06:19 GMT wallaby:project Test run data re-queued
```

```
Postprocessor run failure: ENOENT: no such file or directory, open '/<path-removed>/cache/196e18401b67579637a91b58941ad614b3b1bdcb3c12a6cd5063f831ad665f03/version'
```

**Comment by mzgoddard** [comment]
Pruning old issues.
