### ISSUE TITLE
Plugin fails when using webpack.SourceMapDevToolPlugin directly

### ISSUE THREAD

**Issue by ymichael** [mzgoddard/hard-source-webpack-plugin#141]
If I decide to use webpack.SourceMapDevToolPlugin instead of the devtool option to configure source maps, I get the following exception:

```
 46% [1] chunk asset optimization~/node_modules/hard-source-webpack-plugin/node_modules/source-list-map/lib/fromStringWithSourceMap.js:11
	var sources = map.sources;
	                 ^

TypeError: Cannot read property 'sources' of undefined
    at fromStringWithSourceMap (~/node_modules/hard-source-webpack-plugin/node_modules/source-list-map/lib/fromStringWithSourceMap.js:11:19)
    at HardSource.listMap (~/node_modules/hard-source-webpack-plugin/lib/hard-source.js:57:10)
    at ~/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:51:17
    at Array.forEach (native)
    at ConcatSource.listMap (~/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:47:16)
    at ~/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:51:17
    at Array.forEach (native)
    at ConcatSource.listMap (~/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:47:16)
    at ~/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:51:17
    at Array.forEach (native)
    at ConcatSource.listMap (~/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:47:16)
    at ~/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:51:17
    at Array.forEach (native)
    at ConcatSource.listMap (~/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:47:16)
    at ConcatSource.proto.sourceAndMap (~/node_modules/webpack/node_modules/webpack-sources/lib/SourceAndMapMixin.js:23:16)
    at CachedSource.sourceAndMap (~/node_modules/webpack/node_modules/webpack-sources/lib/CachedSource.js:51:28)
    at ~/node_modules/webpack/lib/SourceMapDevToolPlugin.js:65:35
    at Array.map (native)
    at ~/node_modules/webpack/lib/SourceMapDevToolPlugin.js:52:85
    at Array.forEach (native)
    at Compilation.<anonymous> (~/node_modules/webpack/lib/SourceMapDevToolPlugin.js:51:12)
    at Compilation.applyPlugins1 (~/node_modules/webpack/node_modules/tapable/lib/Tapable.js:75:14)
    at ~/node_modules/webpack/lib/Compilation.js:639:11
    at next (~/node_modules/webpack/node_modules/tapable/lib/Tapable.js:138:11)
    at Compilation.<anonymous> (~/node_modules/webpack/lib/ProgressPlugin.js:117:6)
    at Compilation.applyPluginsAsyncSeries (~/node_modules/webpack/node_modules/tapable/lib/Tapable.js:142:13)
    at ~/node_modules/webpack/lib/Compilation.js:635:10
    at next (~/node_modules/webpack/node_modules/tapable/lib/Tapable.js:138:11)
    at Compilation.<anonymous> (~/node_modules/webpack/lib/ProgressPlugin.js:113:6)
    at Compilation.applyPluginsAsyncSeries (~/node_modules/webpack/node_modules/tapable/lib/Tapable.js:142:13)
```

**Comment by mzgoddard** [comment]
@ymichael Can you post your `SourceMapDevToolPlugin` options?

**Comment by ymichael** [comment]
hey, sure!

I'm using this:

```
            new webpack.SourceMapDevToolPlugin({
                filename: '[file].map[query]',
                moduleFilenameTemplate: undefined,
                fallbackModuleFilenameTemplate: undefined,
                append: null,
                module: true,
                columns: false,
                lineToLine: false,
                noSources: false,
                test: /\.(js|css)(\.out)?($|\?)/i,
            }),
```

which is basically the same as `devtool: 'cheap-module-source-map'` with a custom test regex

**Comment by mzgoddard** [comment]
Cool. I should be able to fix this soon without too much work.

**Comment by ymichael** [comment]
Thanks!
