### ISSUE TITLE
Problem with to-string-loader and postcss-loader

### ISSUE THREAD

**Issue by WiseBird** [mzgoddard/hard-source-webpack-plugin#147]
I have a problem when use these two loaders together.
There is a [repo](https://github.com/WiseBird/hard_source_issue) with minimal setup. Rule:
```
    {
        test: /\.css$/,
        use: [
            'to-string-loader',
            {
                loader: 'postcss-loader',
                options: {
                    plugins: () => [
                        require('autoprefixer')({browsers: 'last 3 Chrome versions'})
                    ]
                }
            }
        ]
    },
```

Do:
* `npm install`
* `./node_modules/.bin/webpack --config webpack.conf.js`
* change `src/base.css`, e.g. clear it
* `./node_modules/.bin/webpack --config webpack.conf.js`

Following error is thrown:
```
ERROR in ./~/postcss-loader/lib?{}!./src/base.css
Module build failed: TypeError: Cannot read property 'postcss' of null
    at Processor.normalize (/home/sergey/projects/basic__webpack/node_modules/postcss/lib/processor.js:136:12)
    at new Processor (/home/sergey/projects/basic__webpack/node_modules/postcss/lib/processor.js:51:25)
    at postcss (/home/sergey/projects/basic__webpack/node_modules/postcss/lib/postcss.js:73:10)
    at Promise.resolve.then.then (/home/sergey/projects/basic__webpack/node_modules/postcss-loader/lib/index.js:137:12)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/base.css 2:21-98
 @ ./src/index.js
```

**Comment by mzgoddard** [comment]
Fixed in #153
