### ISSUE TITLE
TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by ericclemmons** [mzgoddard/hard-source-webpack-plugin#16]
I get the following error when running this a second time:

```
~/node_modules/webpack/lib/ModuleDependencyWarning.js:9
        this.message = loc.start.line + ":" + loc.start.column + " ";
                   ^
TypeError: Cannot read property 'start' of undefined
    at new ModuleDependencyWarning (~/node_modules/webpack/lib/ModuleDependencyWarning.js:9:20)
```

<details>
  <summary>More...</summary>
```
~/node_modules/webpack/lib/ModuleDependencyWarning.js:9
        this.message = loc.start.line + ":" + loc.start.column + " ";
                   ^
TypeError: Cannot read property 'start' of undefined
    at new ModuleDependencyWarning (~/node_modules/webpack/lib/ModuleDependencyWarning.js:9:20)
    at ~/node_modules/webpack/lib/Compilation.js:643:20
    at Array.forEach (native)
    at ~/node_modules/webpack/lib/Compilation.js:642:14
    at Array.forEach (native)
    at ~/node_modules/webpack/lib/Compilation.js:639:22
    at Array.forEach (native)
    at Compilation.reportDependencyWarnings (~/node_modules/webpack/lib/Compilation.js:638:9)
    at Compilation.<anonymous> (~/node_modules/webpack/lib/Compilation.js:497:8)
    at Array.forEach (native)
    at Compilation.finish (~/node_modules/webpack/lib/Compilation.js:496:15)
    at Compiler.<anonymous> (~/node_modules/webpack/lib/Compiler.js:434:15)
    at ~/node_modules/tapable/lib/Tapable.js:152:11
    at Compilation.<anonymous> (~/node_modules/webpack/lib/Compilation.js:444:10)
    at ~/node_modules/webpack/lib/Compilation.js:420:12
    at ~/node_modules/webpack/lib/Compilation.js:332:10
    at ~/node_modules/async/lib/async.js:52:16
    at done (~/node_modules/async/lib/async.js:246:17)
    at ~/node_modules/async/lib/async.js:44:16
    at ~/node_modules/webpack/lib/Compilation.js:332:10
    at ~/node_modules/async/lib/async.js:52:16
    at done (~/node_modules/async/lib/async.js:246:17)
    at ~/node_modules/async/lib/async.js:44:16
    at ~/node_modules/webpack/lib/Compilation.js:332:10
    at ~/node_modules/async/lib/async.js:52:16
    at done (~/node_modules/async/lib/async.js:246:17)
    at ~/node_modules/async/lib/async.js:44:16
    at ~/node_modules/webpack/lib/Compilation.js:332:10
    at ~/node_modules/async/lib/async.js:52:16
    at done (~/node_modules/async/lib/async.js:246:17)
    at ~/node_modules/async/lib/async.js:44:16
    at ~/node_modules/webpack/lib/Compilation.js:332:10
    at ~/node_modules/async/lib/async.js:52:16
    at done (~/node_modules/async/lib/async.js:246:17)
    at ~/node_modules/async/lib/async.js:44:16
    at ~/node_modules/webpack/lib/Compilation.js:332:10
    at ~/node_modules/async/lib/async.js:52:16
    at done (~/node_modules/async/lib/async.js:246:17)
    at ~/node_modules/async/lib/async.js:44:16
    at ~/node_modules/webpack/lib/Compilation.js:332:10
    at ~/node_modules/async/lib/async.js:52:16
    at done (~/node_modules/async/lib/async.js:246:17)
    at ~/node_modules/async/lib/async.js:44:16
    at ~/node_modules/webpack/lib/Compilation.js:332:10
    at ~/node_modules/async/lib/async.js:52:16
    at done (~/node_modules/async/lib/async.js:246:17)
    at ~/node_modules/async/lib/async.js:44:16
    at ~/node_modules/webpack/lib/Compilation.js:332:10
    at ~/node_modules/async/lib/async.js:52:16
    at done (~/node_modules/async/lib/async.js:246:17)
    at ~/node_modules/async/lib/async.js:44:16
    at ~/node_modules/webpack/lib/Compilation.js:332:10
    at ~/node_modules/async/lib/async.js:52:16
    at done (~/node_modules/async/lib/async.js:246:17)
    at ~/node_modules/async/lib/async.js:44:16
    at ~/node_modules/webpack/lib/Compilation.js:332:10
    at ~/node_modules/async/lib/async.js:52:16
    at done (~/node_modules/async/lib/async.js:246:17)
    at ~/node_modules/async/lib/async.js:44:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```
</details>

What can I provide to make this more useful? (I'm using the example on the homepage, nearly verbatim)

Also, this project has:

- Code-splitting via `require.ensure`.
- `require.context` in several places.
- `babel-loader`, and a few others.

When checking out `records.json`, I'd wager that the files referenced via `require.context` strike me as the outliers:

```json
{
  "modules": {
    "byIdentifier": {
      "node_modules/react/react.js": "./node_modules/react/react.js",
      "src/routes/docs /\\.js$": 0,
      "multi client": 1,
      "multi widgets": 2,
      "src/components /\\.fixture\\.js$": 3,
      "src/components /\\/[A-Z]\\w+\\.js$": 4,
      // ...a bunch of /node_module/something: node_modules/something
    },
    "usedIds": {
      "0": 0,
      "1": 1,
      "2": 2,
      "3": 3,
      "4": 4,
      "5": 5,
      "./node_modules/react/react.js": "./node_modules/react/react.js",
      // a bunch of ./some/path.js: ./some/path.js
    }
  },
  "chunks": {
    "byName": {
      "client": 5,
      "widgets": 6
    },
    "byBlocks": {
      "node_modules/babel-loader/index.js?{\"cacheDirectory\":true,\"env\":{\"development\":{\"plugins\":[[\"react-transform\",{\"transforms\":[{\"transform\":\"react-transform-hmr\",\"imports\":[\"react\"],\"locals\":[\"module\"]}]}]]}}}!node_modules/eslint-loader/index.js!src/routes/index.js:0/1": 0,
      "node_modules/babel-loader/index.js?{\"cacheDirectory\":true,\"env\":{\"development\":{\"plugins\":[[\"react-transform\",{\"transforms\":[{\"transform\":\"react-transform-hmr\",\"imports\":[\"react\"],\"locals\":[\"module\"]}]}]]}}}!node_modules/eslint-loader/index.js!src/routes/index.js:1/1": 1,
      "node_modules/babel-loader/index.js?{\"cacheDirectory\":true,\"env\":{\"development\":{\"plugins\":[[\"react-transform\",{\"transforms\":[{\"transform\":\"react-transform-hmr\",\"imports\":[\"react\"],\"locals\":[\"module\"]}]}]]}}}!node_modules/eslint-loader/index.js!src/routes/components/index.js:0/0": 2,
      "node_modules/babel-loader/index.js?{\"cacheDirectory\":true,\"env\":{\"development\":{\"plugins\":[[\"react-transform\",{\"transforms\":[{\"transform\":\"react-transform-hmr\",\"imports\":[\"react\"],\"locals\":[\"module\"]}]}]]}}}!node_modules/eslint-loader/index.js!src/routes/dashboard/index.js:0/0": 3,
      "node_modules/babel-loader/index.js?{\"cacheDirectory\":true,\"env\":{\"development\":{\"plugins\":[[\"react-transform\",{\"transforms\":[{\"transform\":\"react-transform-hmr\",\"imports\":[\"react\"],\"locals\":[\"module\"]}]}]]}}}!node_modules/eslint-loader/index.js!src/routes/login/index.js:0/0": 4
    },
    "usedIds": {
      "0": 0,
      "1": 1,
      "2": 2,
      "3": 3,
      "4": 4,
      "5": 5,
      "6": 6
    }
  },
  "prepreHash": "x",
  "preHash": "bb85840e4b6505f91209",
  "hash": "806005adce5d53614746",
  "moduleHashs": {
```

**Comment by mzgoddard** [comment]
@ericclemmons This is already useful. Thank you. This is clearly something I've overlooked and need to do some work to support.

I'm guessing you are getting a warning in your first run and in the second run the warning is persisting correctly but the plugin isn't caching needed metadata for this warning to work without erroring.

From what've you posted I'm guessing you are using webpack 2 and harmony modules. I'm guessing that because those are the likely dependencies who would create dependency warnings. Specifically you probably have an `import` statement for a export from a dependency that doesn't export the desired field. Like `import {key} from './file'` when `file` doesn't export `key`. If I'm wrong on this, if you can figure out the dependency with the warning that would be great info to add.

**Comment by MoOx** [comment]
I am getting a similar issue.

```
/..../node_modules/loader-runner/lib/LoaderRunner.js:90
                        throw e;
                        ^

TypeError: Cannot read property 'start' of undefined
    at new ModuleDependencyWarning (/..../node_modules/webpack/lib/ModuleDependencyWarning.js:9:20)
    at /..../node_modules/webpack/lib/Compilation.js:643:20
    at Array.forEach (native)
    at /..../node_modules/webpack/lib/Compilation.js:642:14
    at Array.forEach (native)
    at /..../node_modules/webpack/lib/Compilation.js:639:22
    at Array.forEach (native)
    at Compilation.reportDependencyWarnings (/..../node_modules/webpack/lib/Compilation.js:638:9)
    at Compilation.<anonymous> (/..../node_modules/webpack/lib/Compilation.js:497:8)
    at Array.forEach (native)
    at Compilation.finish (/..../node_modules/webpack/lib/Compilation.js:496:15)
    at Compiler.<anonymous> (/..../node_modules/webpack/lib/Compiler.js:434:15)
    at /..../node_modules/tapable/lib/Tapable.js:152:11
    at Compilation.<anonymous> (/..../node_modules/webpack/lib/Compilation.js:444:10)
    at /..../node_modules/webpack/lib/Compilation.js:420:12
    at /..../node_modules/webpack/lib/Compilation.js:332:10
```

I am using webpack 2 with "import"s.
First (no cache) compilation works fine (not even a warning)

```
Environment has changed (node_modules or configuration was updated).
HardSourceWebpackPlugin will reset the cache and store a fresh one.
```

But when I restart (so cache is used) I got the error above.

**Comment by ericclemmons** [comment]
@mzgoddard Using the latest `master` (with #20) in it, I see warnings such as:

>  WARNING in ./src/client.js
    15:2 export 'Provider' (imported as 'Redux') was not found in './stores/ApiStore'

The original source is:

```js
import { Provider as Mobx } from "mobx-react";
import { browserHistory, Router } from "react-router";
import DOM from "react-dom";
import { enhance } from "react-router-enhanced-routes";
import { Provider as Redux } from "react-redux";
import React from "react";

import configureStore from "./configureStore";
import routes from "./routes";
import ApiStore from "./stores/ApiStore";

const store = configureStore(window.__INITIAL_STATE__);

DOM.render((
  <Redux store={store}> // Line 15
    <Mobx api={new ApiStore()}>
      <Router
        history={browserHistory}
        routes={enhance(routes, { store })}
      />
    </Mobx>
  </Redux>
), document.getElementById("mount"));
```
    
Yes, this is using `.babelrc`:

```json
{
  "presets": [
    ["es2015", { "modules": false }],
    "react",
    "stage-0"
  ],
  "plugins": [
    "lodash",
    "react-html-attrs",
    "transform-decorators-legacy"
  ]
}
```

And I'm also using Webpack 2's `resolve.root = ["./lib", "node_modules"]` based off of this post (for Webpack 1):
> https://medium.com/@ericclemmons/dogfooding-your-open-source-projects-9e6dc1e7d1c8

I even get similar warnings for `bindActionCreators` against this code:

```js
import { bindActionCreators } from "redux";
import * as trackingActions from "./actions";
import configureTrackingStore from "./configureStore";

const userToken = `asdf1234`;

const trackingStore = configureTrackingStore(
  userToken,
  { actionCount: 0 }
);

export default bindActionCreators(
  trackingActions,
  trackingStore.dispatch
);
```

It seems to be anything with a named import.

Any ideas?

**Comment by mzgoddard** [comment]
@ericclemmons Thanks for bringing up this follow up.

Yeah its anything that webpack creates a `HarmonyImportSpecifierDependency` of `HarmonyExportImportedSpecifierDependency`. These dependencies refer to their dependency that points at their related modules. HardSource isn't connecting to the right dependency. It'd only work if the last import was the only one with a specifier. HardSource needs to store a little more info and use that to stand up the right dependency graph for a module.

Which #23 does. :smile:
