### ISSUE TITLE
Successive builds fail for nested async dependency requests

### ISSUE THREAD

**Issue by lewismoten** [mzgoddard/hard-source-webpack-plugin#176]
The first time succeeds, all builds afterwards fail.

I ran webpack with the default setting.
```javascript
{
  plugins: [
    new HardSourceWebpackPlugin()
  }
}
```

The first build was fine and said it was writing to a new confighash path for the first time. The build completed 50% longer than usual builds without the plugin. The second build resulted in the following error:

```
[14:53:09] Starting 'webpack'...
C:\my-project\node_modules\webpack\lib\Stats.js:390
module: origin.module ? origin.module.identifier() : "",
                                      ^

TypeError: origin.module.identifier is not a function
    at obj.origins.chunk.origins.map.origin (C:\my-project\node_modules\webpack\lib\Stats.js:390:45)
    at Array.map (native)
    at obj.chunks.compilation.chunks.map.chunk (C:\my-project\node_modules\webpack\lib\Stats.js:388:34)
    at Array.map (native)
    at Stats.toJson (C:\my-project\node_modules\webpack\lib\Stats.js:364:36)
    at WebpackPlugin.compileCallback (C:\my-project\node_modules\piped-webpack\lib\webpackPlugin.js:107:22)
    at compile_method (C:\my-project\node_modules\piped-webpack\lib\webpackPlugin.js:96:9)
    at emitRecords.err (C:\my-project\node_modules\webpack\lib\Compiler.js:269:13)
    at MemoryFileSystem.writeFile (C:\my-project\node_modules\memory-fs\lib\MemoryFileSystem.js:328:9)
    at Compiler.writeFile (C:\my-project\node_modules\webpack\lib\Compiler.js:388:26)
    at outputFileSystem.mkdirp.err (C:\my-project\node_modules\webpack\lib\Compiler.js:384:14)
    at Immediate.<anonymous> (C:\my-project\node_modules\memory-fs\lib\MemoryFileSystem.js:288:4)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

Operating System: Windows 7
Packages:
- node: 6.11.2
- npm: 5.2.0
- webpack: 3.6.0
- piped-webpack: 1.2.0
- hard-source-webpack-plugin: 0.4.9

**Comment by lewismoten** [comment]
I found how to reproduce the issue. It seems to be related to having nested async requires within one another. When I remove the HardSourceWebpackPlugin everything works fine.

for the gulp task:
```javascript
var gulp = require("gulp");
var gutil = require("gulp-util");
var pipedWebpack = require("piped-webpack");
var HardSourceWebpackPlugin = require("hard-source-webpack-plugin");
var config = {
        entry: {
            main: "./gulp/test1.js"
        },
        output: {
            publicPath: "./dist/",
            filename: "harbinger.[name].js",
            pathinfo: true
        },
        plugins: [
            new HardSourceWebpackPlugin()
        ]
};
gulp.task("break-it", () => gulp
        .src([])
        .pipe(pipedWebpack(config).on("error", gutil.log))
        .pipe(gulp.dest("dist/"))
    );
```
**File:** test1.js
```javascript
require(["./test2.js"], function(test2) {
    require(["./test3.js"], function(test3) {
        console.log("all files loaded");
    });
});
```
**File:** test2.js
```javascript
console.log("this is test 2");
```
**File:** test3.js
```javascript
console.log("this is test 3");
```
I've tried both types of async requires and had the same problems:
```javascript
require(
  [path1, path2],
  function(dep1, dep2){ 
    // foo 
});
require.ensure(
  [path1, path2], 
  function(require) {
    require(path1); 
    require(path2)
  }
);
```

**Comment by mzgoddard** [comment]
@lewismoten Thanks for the reproduction. That helped a lot.
