### ISSUE TITLE
Compatibility issues with webpack 3.8.1

### ISSUE THREAD

**Issue by rowanoulton** [mzgoddard/hard-source-webpack-plugin#184]
Ahoy!

We're avid users of this plugin but are blocked from upgrading to webpack 3.8.1 because of what appear to be some slight differences in webpack's new internals:

```
/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:60
				if(this.activeExports.has(id)) return false;
				                     ^

TypeError: Cannot read property 'has' of null
    at importedNames.originModule.usedExports.filter.id (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:60:26)
    at Array.filter (<anonymous>)
    at HardHarmonyExportImportedSpecifierDependency.getReference (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:58:56)
    at processDependency (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:52:48)
    at depBlock.dependencies.forEach.dep (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:46:43)
    at Array.forEach (<anonymous>)
    at processDependenciesBlock (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:46:28)
    at Compilation.compilation.plugin.modules (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:23:6)
    at Compilation.applyPluginsBailResult1 (/Users/rowanoulton/Projects/webapp/node_modules/webpack/node_modules/tapable/lib/Tapable.js:140:27)
    at Compilation.seal (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/Compilation.js:597:9)
    at applyPluginsParallel.err (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/Compiler.js:508:17)
    at /Users/rowanoulton/Projects/webapp/node_modules/webpack/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

If I can find some time I'll have a crack at crafting a fix. Wanted to post this here in the meantime in case others are experiencing the issue.

Thanks for all the great work! ✌

**Comment by OlegLustenko** [comment]
It doesn't help
First webpack run is fine and second throw an error

Webpack migrates arrays to Map and Sets, seems some structure doesn't play well.
