### ISSUE TITLE
Compatibility issues with webpack 3.8.1

### ISSUE THREAD

**Issue by rowanoulton** [mzgoddard/hard-source-webpack-plugin#190]
Re-opening #184 as my patch didn't seem to help 😞 

[Oleg is right](https://github.com/mzgoddard/hard-source-webpack-plugin/issues/184#issuecomment-341056602) that webpack has changed to Sets and makes use of `.has` which could cause problems if hard-source is thawing arrays. I'm not entirely sure why `activeExports` would be null here though:

```
/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:60
				if(this.activeExports.has(id)) return false;
				                     ^

TypeError: Cannot read property 'has' of null
    at importedNames.originModule.usedExports.filter.id (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:60:26)
    at Array.filter (<anonymous>)
    at HardHarmonyExportImportedSpecifierDependency.getReference (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:58:56)
    at processDependency (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:52:48)
    at depBlock.dependencies.forEach.dep (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:46:43)
    at Array.forEach (<anonymous>)
    at processDependenciesBlock (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:46:28)
    at Compilation.compilation.plugin.modules (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:23:6)
    at Compilation.applyPluginsBailResult1 (/Users/rowanoulton/Projects/webapp/node_modules/webpack/node_modules/tapable/lib/Tapable.js:140:27)
    at Compilation.seal (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/Compilation.js:597:9)
    at applyPluginsParallel.err (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/Compiler.js:508:17)
    at /Users/rowanoulton/Projects/webapp/node_modules/webpack/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Any theories?

**Comment by ohze** [comment]
`activeExports === null` is caused by [this line](https://github.com/mzgoddard/hard-source-webpack-plugin/blob/version-0-4/lib/dependencies.js#L147):
```
new HarmonyExportImportedSpecifierDependency(originModule, importDependency, null, id, name, null),```
When I change the last argument from `null` to `new Set()` then its actually work but there are some WARNING, ex:
```
WARNING in ./node_modules/pako-es/lib/zlib/inflate.js
1117:14-27 "export 'default' (imported as 'inflate_table') was not found in './inftrees'
 @ ./node_modules/pako-es/lib/zlib/inflate.js
 @ ./node_modules/pako-es/lib/inflate.js
 @ ./node_modules/pako-es/index.js
 ...
 @ ./src/index.ts
 @ multi babel-polyfill ./src/index.ts

WARNING in <removed>
5:128815-128825 "export 'default' (imported as 'DataStream') was not found in 'datastream-js'
 ...
 @ ./src/index.ts
 @ multi babel-polyfill ./src/index.ts
```

All warning is from the module that has `module` key in its `package.json`

**Comment by ohze** [comment]
TIP: We can debug `hard-source-webpack-plugin` with WebStorm by right-click on `release-web-debug` npm script line (in a project that use `hard-source-webpack-plugin`):
```json
{
  "scripts": {
    "release-web-debug": "node $NODE_DEBUG_OPTION `which webpack`"
  }
}
```
