### ISSUE TITLE
TypeError: Cannot read property 'global' of null

### ISSUE THREAD

**Issue by filipesilva** [mzgoddard/hard-source-webpack-plugin#198]
Heya, I was trying to use `HardSourceWebpackPlugin` and I get an odd error on the second build:

```
kamik@T460p MINGW64 /d/sandbox/master-project (master)$ ng build --no-progress
D:\sandbox\master-project\node_modules\webpack\lib\dependencies\ContextDependency.js:19
                if(this.regExp.global || this.regExp.sticky) {
                               ^

TypeError: Cannot read property 'global' of null
    at new ContextDependency (D:\sandbox\master-project\node_modules\webpack\lib\dependencies\ContextDependency.js:19:18)
    at new HardContextDependency (D:\sandbox\master-project\node_modules\hard-source-webpack-plugin\lib\dependencies.js:50:7)
    at Object.<anonymous> (D:\sandbox\master-project\node_modules\hard-source-webpack-plugin\lib\deserialize-dependencies.js:22:17)
    at Array.map (<anonymous>)
    at Object.deserializeDependencies (D:\sandbox\master-project\node_modules\hard-source-webpack-plugin\lib\deserialize-dependencies.js:20:15)
    at HardModule.build (D:\sandbox\master-project\node_modules\hard-source-webpack-plugin\lib\hard-module.js:144:60)
    at D:\sandbox\master-project\node_modules\hard-source-webpack-plugin\index.js:1486:18
    at Array.map (<anonymous>)
    at preload (D:\sandbox\master-project\node_modules\hard-source-webpack-plugin\index.js:1463:6)
    at Compiler.<anonymous> (D:\sandbox\master-project\node_modules\hard-source-webpack-plugin\index.js:1542:9)
    at Compiler.applyPluginsParallel (D:\sandbox\master-project\node_modules\tapable\lib\Tapable.js:275:14)
    at applyPluginsAsync.err (D:\sandbox\master-project\node_modules\webpack\lib\Compiler.js:503:9)
    at Compiler.applyPluginsAsyncSeries (D:\sandbox\master-project\node_modules\tapable\lib\Tapable.js:177:46)
    at Compiler.compile (D:\sandbox\master-project\node_modules\webpack\lib\Compiler.js:496:8)
    at readRecords.err (D:\sandbox\master-project\node_modules\webpack\lib\Compiler.js:283:11)
    at Array.inputFileSystem.readFile (D:\sandbox\master-project\node_modules\webpack\lib\Compiler.js:412:12)
    at Storage.finished (D:\sandbox\master-project\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:40:15)
    at D:\sandbox\master-project\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:77:9
    at D:\sandbox\master-project\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

It's hard to isolate the webpack config because this it's generated on the fly by https://github.com/angular/angular-cli (I'm one of the maintainers).

Do you have an idea of what can cause this error? Maybe I can take it from there. I can get you a repro but the config would be somewhat of a mess as our ejected configs are auto generated.

If there's anything I can do to help debug this, let me know.

**Comment by filipesilva** [comment]
Was debugging the issue and found out the fix is already in master (https://github.com/mzgoddard/hard-source-webpack-plugin/pull/189), but hasn't been released yet and that's why I wasn't getting it. Cheers!
