### ISSUE TITLE
memory issue on 0.4.12 / 0.5.0-rc.4

### ISSUE THREAD

**Issue by zanettin** [mzgoddard/hard-source-webpack-plugin#205]
as mentioned on #202 :

facing these issues running `0.4.12` and `0.5.0-rc.4`:

```
Starting the development server...

[hard-source:core] HardSourceWebpackPlugin is writing to a new confighash path for the first time: /Users/myApp/node_modules/.cache/hard-source/fdc902b4c070f79b25e3fe2981d322915153030cd5d58a8bea493f96b1a91390

<--- Last few GCs --->

[14422:0x102802400]    43872 ms: Mark-sweep 1405.5 (1584.9) -> 1405.2 (1584.9) MB, 234.9 / 0.0 ms  allocation failure GC in old space requested
[14422:0x102802400]    44112 ms: Mark-sweep 1405.2 (1584.9) -> 1405.1 (1545.9) MB, 240.5 / 0.0 ms  last resort GC in old space requested
[14422:0x102802400]    44344 ms: Mark-sweep 1405.1 (1545.9) -> 1405.1 (1537.4) MB, 231.5 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3447d96a5e91 <JSObject>
    0: builtin exit frame: stringify(this=0x3447d9688ff1 <Object map = 0x344786e82ba1>,0x344774302311 <undefined>,0x344774302311 <undefined>,0x344761e7f5b9 <JSArray[2]>)

    1: arguments adaptor frame: 1->3
    2: /* anonymous */ [/Users/myApp/node_modules/hard-source-webpack-plugin/lib/hard-basic-dependency-plugin.js:~86] [pc=0x35da07b9dc60](this=0x344733b3b649 ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/Roman/.nvm/versions/node/v8.8.0/bin/node]
```

after allocating more memory `--max-old-space-size=4096`:

```
Starting the development server...

[hard-source:core] HardSourceWebpackPlugin is writing to a new confighash path for the first time: /Users/myApp/node_modules/.cache/hard-source/fdc902b4c070f79b25e3fe2981d322915153030cd5d58a8bea493f96b1a91390
/Users/myAPp/node_modules/hard-source-webpack-plugin/lib/hard-basic-dependency-plugin.js:99
      var _inContextDependencyIdentifier = module && JSON.stringify([module.context, frozen]);
                                                          ^

RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at Compiler.<anonymous> (/Users/myApp/node_modules/hard-source-webpack-plugin/lib/hard-basic-dependency-plugin.js:99:59)
```

node: `8.8`
npm: `5.4.2`
webpack: `3.10.0`

# your questions:
### what loaders and plugins your project is using?

develop build
```
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CaseSensitivePathsPlugin = require('case-sensitive-paths-webpack-plugin');
const InterpolateHtmlPlugin = require('react-dev-utils/InterpolateHtmlPlugin');
const WatchMissingNodeModulesPlugin = require('react-dev-utils/WatchMissingNodeModulesPlugin');
const eslintFormatter = require('react-dev-utils/eslintFormatter');
const ModuleScopePlugin = require('react-dev-utils/ModuleScopePlugin');
const HardSourceWebpackPlugin = require('hard-source-webpack-plugin');
```

production build
```
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const ManifestPlugin = require('webpack-manifest-plugin');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
const InterpolateHtmlPlugin = require('react-dev-utils/InterpolateHtmlPlugin');
const SWPrecacheWebpackPlugin = require('sw-precache-webpack-plugin');
const LodashModuleReplacementPlugin = require('lodash-webpack-plugin');
const eslintFormatter = require('react-dev-utils/eslintFormatter');
const ModuleScopePlugin = require('react-dev-utils/ModuleScopePlugin');
const nodeExternals = require('webpack-node-externals');
const HardSourceWebpackPlugin = require('hard-source-webpack-plugin');
```

### number of modules being built?
| env | modules count |
| -- | -- |
| develop | 2 (main and vendors) |
| production | 3 (node, main and vendors) |

### how big is the output js files normally?
| env | file size |
| -- | -- |
| develop | unknown (`webpack-dev-server`) |
| production | main (725kb), vendors (683kb), node (5.5mb) |

### size of the output destination all together?
| env | build dir size |
| -- | -- |
| develop | unknown (`webpack-dev-server`) |
| production | ~47mb |

if you need any further info, just give me a note. thx

**Comment by mzgoddard** [comment]
> number of modules being built?

For `modules`, here I mean how many files were built into the files. The answer you gave for modules, would be called entries (or could be referred to as chunks too). The number of modules is a common item in the webpack cli output. No worries if you need to dig for it and are not sure where best to get it.

---

Thank for the loader and plugin info. It'll take some digging to see if any of those contribute to the issue.

@zanettin I haven't seen `RangeError: Invalid string length` before. That's pretty wild. I did some digging based on this error this morning and found my own result echoing [this handlebars issue](https://github.com/wycats/handlebars.js/issues/1283). The error is pretty literal, JS is trying to create a string larger than some size that V8 will not create, either because its a hard coded value or system specific. For my systems it was something larger than 138MB.

That's pretty useful info since it means we're working with some really big strings. I just wouldn't expect those big strings to come from stringify-ing a frozen dependency with a module context. I'm kind of stumped how freezing a dependency could make a string big enough for that error to be thrown.

So that's making me think its a side effect of probably a bunch of other large strings existing at the same time.

On that front I expect a few items will culprits for making large strings. Each module, serializes some of the same large amounts of info a few times.

- The built module source is "serialized" twice
- And a third time for the hashContent so the chunk and build hashes are the same between builds (with and without hard-source enabled)
- The source map is always saved for Stats object support
- And a second source map if source maps are enabled

Without going into why those different renderings of the source and source map are needed for transparent support of different webpack features, i think we can disable all but one of the built sources to see if that improves the build behaviour for you. And figure out how we can use that info later if that helps.

With `hard-source@0.5`'s partial plugin support we can disable the extra source and maps with a plugin.

Try putting this in your webpack config in the plugins array after hard-source.

```js
{
  apply: function(compiler) {
    compiler.plugin('--hard-source-after-freeze-module', function(frozen, module, extra) {
      if (frozen) {
        frozen.rawSource = '';
        frozen.hashContent = '';
        frozen.sourceMap.baseMap = null;
      }
      return frozen;
    });
  }
},
```

Another thought I have to try is to omit files from being cached. The following is a simple test plugin for that. It's not useful outside of testing hard-source without modification as disabling cache-ability this way will degrade normal webpack performance too, not just hard-source's.

```js
{
  apply: function(compiler) {
    compiler.plugin('--hard-source-before-freeze-module', function(frozen, module, extra) {
      if (
        module.cacheable &&
        (
          !/\.js$/.test(module.request) ||
          /node_modules/.test(module.request)
        )
      ) {
        module.cacheable = false;
        return null;
      }
      return frozen;
    });
  }
},
```

**Comment by zanettin** [comment]
> For modules, here I mean how many files were built into the files.

Ah sorry! tried to read stats from dev and prod builds. maybe that is what you're looking for?
Just added counts of `assets.length` and `chunks[x].modules.length`.

**executed**
`NODE_ENV=development  ./node_modules/.bin/webpack --config=config/webpack.config.dev.js  --profile --json > stats-dev.json`
`NODE_ENV=production ./node_modules/.bin/webpack --config=config/webpack.config.prod.js  --profile --json > stats-prod.json`

**counts**

| env | assets | chunk 1 | chunk 2 | chunk 3 |
| --- | --- | --- | --- | --- |
| dev client | 182 | 206 | 1399 | n/a |
| prod client | 187 | 182 | 463 | 291 |
| prod node | 182 | 1034 | n/a | n/a |

---

> Try putting this in your webpack config in the plugins array after hard-source.

Added this right after the `hard-source` plugin had no effect on dev nor prod 🙈 

> Another thought I have to try is to omit files from being cached

First build went smoothly. Second (cached one) failed because of not resolvable postcss files.
```
Error: ./src/myApp/screens/App/components/Teaser/components/TeaserSmallt/components/Default/styles.css
Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property 'postcss' of null
    at <anonymous>
    at <anonymous>
    at compiler.run (/Users/myApp/scripts/build.js:153:23)
    at emitRecords.err (/Users/myApp/node_modules/webpack/lib/Compiler.js:265:13)
    at /Users/myApp/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:137:15)
```

**Comment by KnisterPeter** [comment]
We have this error as well:
```shell
RangeError: Invalid string length
    at Object.stringify (native)
    at Compiler.<anonymous> (/home/marwol/src/ml-webclient/node_modules/hard-source-webpack-plugin/lib/hard-basic-dependency-plugin.js:99:59)
    at Compiler.applyPluginsWaterfall (/home/marwol/src/ml-webclient/node_modules/tapable/lib/Tapable.js:92:24)
    at freeze (/home/marwol/src/ml-webclient/node_modules/hard-source-webpack-plugin/index.js:1482:25)
    at /home/marwol/src/ml-webclient/node_modules/hard-source-webpack-plugin/index.js:1506:18
```

In our case the number of modules is around 6000. So I guess the webpack context is really huge.

**Comment by mzgoddard** [comment]
@KnisterPeter thanks for the stack trace. The error you are getting may not be because of a huge context but of something that when `JSON.stringify`'d is trying to make a single string >100MB. Nothing that `hard-source` freezes should be that big so there is either a bug or something being frozen with an unintended member that refers back to a larger portion of the graph (which yeah would be affected by the number of modules).

Reading the relevant code I haven't found anything obivous that is being stringified.

@KnisterPeter @zanettin I'm going to add a patch soon that will catch errors whiling freezing modules and chucking them while logging a warning that the module couldn't be frozen and the error that caused that. That won't be a solution, making such a large string uses a lot of time. But this will give us the module(s) that are breaking and hopefully we can figure out more from that.

---

> Module build failed: TypeError: Cannot read property 'postcss' of null

@zanettin what postcss loader, postcss plugins and postcss related webpack plugins are you using? Seems a module is rebuilding that might be looking at another built but frozen module for postcss info. And the frozen module doesn't have that info on it because it needs a plugin for hard source to freeze and that that data on the module. I'm guessing its a cached postcss AST its looking for on a nested object on the module.

You might also be able to tweak that second plugin's regex to exclude the modules that are looking up the postcss data. But I'd figure that'd be a plugin. If its a plugin to optimize things you might be able to disable the plugin and see if that builds. I don't mean disabling the plugin as a solution just debugging.

It'll be cool if we need to make a hard source plugin to freeze and thaw the missing postcss info. :smile: I figured that'd be an eventual need and the rason why hard source now supports that with more to come on the plugin front.

**Comment by ld-gary** [comment]
Hey, I'm also seeing this issue very suddenly. Pretty much stopping work of any kind atm. hard-source is only being used on my dev build, which is failing, whereas my production build is fine and doesn't use hard-source. Could be something I'm missing in my code but thought I should raise the issue here as it appears to be live going from very recent comments...

`/MY/DIR/PATH/node_modules/hard-source-webpack-plugin/index.js:1561
          value: JSON.stringify(item),
                      ^
RangeError: Invalid string length`

**Comment by mzgoddard** [comment]
@zanettin @KnisterPeter @ld-gary I've added a point of error logging around the module freezing in `0.5.6` from #222. If y'all can give that a try, it will let us know what module(s) are experiencing the error and give us a more isolated area to dig around. Given the stack traces so far its probably one of the dependencies serializing info for validating the module in the next build.

**Comment by zanettin** [comment]
Hi @mzgoddard 

Thx a lot for all your work. Upgraded to latest delivers following output (using `--max-old-space-size=4096`):

### develop
1. build => no errors 👍 
2. build => seams like just apollo graphql is not hard source conform 😄 
```
Starting the development server...
[hard-source:serial] Unable to freeze module "./node_modules/apollo-link-http/node_modules/apollo-utilities/lib/index.js". An error occured serializing it into a string: Invalid string length

[hard-source:serial] Unable to freeze module "./node_modules/apollo-link/node_modules/apollo-utilities/lib/index.js". An error occured serializing it into a string: Invalid string length

[hard-source:serial] Unable to freeze module "./node_modules/apollo-utilities/lib/index.js". An error occured serializing it into a string: Invalid string length
```

### production
1. build => no errors 👍 
2. build => same as `dev` + server.js (target node) `113 modules`
```
Creating an optimized production build for target "browser"...
Creating an optimized production build for target "node"...

[hard-source:serial] Unable to freeze module "./src/gaultmillau/entry/server/render.js + 113 modules". An error occured serializing it into a string: Invalid string length

[hard-source:serial] Unable to freeze module "./node_modules/apollo-utilities/lib/index.js + 11 modules". An error occured serializing it into a string: Invalid string length

[hard-source:serial] Unable to freeze module "./node_modules/apollo-client/index.js + 28 modules". An error occured serializing it into a string: Invalid string length

[hard-source:serial] Unable to freeze module "./node_modules/apollo-link-http/lib/index.js + 16 modules". An error occured serializing it into a string: Invalid string length
```

hope you can use this info for further investigation. otherwise just tell me what I can check else. thx

**Comment by mzgoddard** [comment]
@zanettin Thanks for running `0.5.6`. I was able to reproduce with the errors you posted. The issue is a pretty complex series of things working together. The short way to think about it was that modules were exporting and import `*`. Normally alone that wouldn't have caused the issue but `apollo-utilities` depends on other modules that depend on other modules this way. This clearly pointed out to me that hard-source was caching data here it didn't need. So #223 caching the part of the dependency that refers to a module. This part of the caching doesn't need to store the export and import names so this should fix the issue for at least `apollo-utilities` and similar modules.

**Comment by mzgoddard** [comment]
@zanettin @KnisterPeter @ld-gary alright, fix is in `0.5.7`. Let me know if that works.

**Comment by zanettin** [comment]
@mzgoddard works like a charm!
build time on dev reduced from 0:58s to 0:08 😍 
build time on prod reduced from 2:47 to 0:47s 😍 
thx a lot!

**Comment by KnisterPeter** [comment]
@mzgoddard now we get an out of memory. But at least this is a more undestandable error.

**Comment by mzgoddard** [comment]
@KnisterPeter if you can, can you list any large by size or large by dependency tree modules or packages? You can build a webpack stats json with `webpack --json >stats.json` and drop the output in to http://webpack.github.io/analyse/ to help find that info.

I'm looking into some memory profiles of my projects with HardSource to see where memory is used for it. If there are public modules in your project that are contributing to the memory error that'll help me debug this and fix it.

**Comment by GoodForOneFare** [comment]
The `0.5.8` release fixes all memory issues for me 👍  Thank you so much for this outstanding plugin!

**Comment by mzgoddard** [comment]
@GoodForOneFare oh dang you're fast. I was about to come mention the patch here. Glad to hear it fixed things for you.

@KnisterPeter just published `0.5.8` with a bunch of memory and speed fixes. Let me know if that helps.

**Comment by KnisterPeter** [comment]
@mzgoddard awesome it is working now. And with a valid cache the rebuild times are reduced from 120s to 20s. :+1:

**Comment by ld-gary** [comment]
@mzgoddard Hey, sorry, bad form to bail on an issue thread. I had just commented hard source out of the process to keep my project's ball rolling. Having added hard source back in things appear to be working well. Thanks for sorting!

**Comment by JWesorick** [comment]
I'm on 0.5.15 and am getting these errors.

**Comment by mischkl** [comment]
On 0.5.18 and also getting the "invalid string length" error sporadically.
