### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by MoOx** [mzgoddard/hard-source-webpack-plugin#22]
I just upgraded from v.28 to v.32 and got this

```
Unhandled rejection TypeError: Cannot read property 'forEach' of undefined
    at walkDependencyBlock (/.../phenomic/node_modules/hard-source-webpack-plugin/index.js:290:27)
    at /.../phenomic/node_modules/hard-source-webpack-plugin/index.js:307:9
    at Array.forEach (native)
    at /.../phenomic/node_modules/hard-source-webpack-plugin/index.js:299:32
    at tryCatcher (/.../phenomic/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/.../phenomic/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/.../phenomic/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/.../phenomic/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/.../phenomic/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/.../phenomic/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/.../phenomic/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/.../phenomic/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/.../phenomic/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/.../phenomic/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/.../phenomic/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/.../phenomic/node_modules/bluebird/js/release/promise.js:636:18)
```

What can I give you to help more?

**Comment by mzgoddard** [comment]
If you could edit the plugin and log out the block on the line before and post that here, if it isn't proprietary.

Though I'm guessing your cache wasn't invalidated and the block is the list of file dependencies for all compilations. `0.0.31` moved file dependencies to a separate cache to get rid of something that'd make pluginifying this plugin harder. (or rather harder for others to write plugins for.)

**Comment by MoOx** [comment]
Phenomic is open source :) http://phenomic.io/

But ok, will try to clean cache and check.

**Comment by MoOx** [comment]
Indeed, cleaning the cache "fixed" the issue. Now I have some others :D
