### ISSUE TITLE
Recusion problem with webpack 4

### ISSUE THREAD

**Issue by KnisterPeter** [mzgoddard/hard-source-webpack-plugin#283]
Hi,

when updating to webpack 4 and using hard-source-webpack-plugin we will end up with this error:

```sh
RangeError: Maximum call stack size exceeded
    at freezeDependency (/home/marwol/src/ml-webclient/node_modules/hard-source-webpack-plugin/lib/hard-basic-dependency-plugin.js:295:26)
    at /home/marwol/src/ml-webclient/node_modules/hard-source-webpack-plugin/lib/hard-basic-dependency-plugin.js:391:21
    at SyncWaterfallHook.eval [as call] (eval at create (/home/marwol/src/ml-webclient/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:7:16)
    at Object.exports.call (/home/marwol/src/ml-webclient/node_modules/hard-source-webpack-plugin/lib/util/plugin-compat.js:80:22)
    at freeze (/home/marwol/src/ml-webclient/node_modules/hard-source-webpack-plugin/index.js:1525:29)
    at /home/marwol/src/ml-webclient/node_modules/hard-source-webpack-plugin/index.js:1550:18
    at Array.map (<anonymous>)
    at mapMap (/home/marwol/src/ml-webclient/node_modules/hard-source-webpack-plugin/index.js:1549:22)
    at mapFreeze (/home/marwol/src/ml-webclient/node_modules/hard-source-webpack-plugin/index.js:1556:14)
    at /home/marwol/src/ml-webclient/node_modules/hard-source-webpack-plugin/lib/hard-dependency-block-plugin.js:145:32

```

This is our configuration
```js
        new HardSourceWebpackPlugin({
            cacheDirectory: path.resolve(
                process.cwd(),
                'node_modules/.cache/hard-source/[confighash]'
            ),
            configHash: function(webpackConfig) {
                return require('node-object-hash')({ sort: false }).hash(
                    webpackConfig, // the whole wepack config export
                    IS_DEV, // boolean
                    IS_E2E, // boolean
                    LOCALDEV, // boolean
                    GITBRANCH // string
                );
            },
            environmentHash: {
                root: process.cwd(),
                directories: [],
                files: ['package-lock.json', 'yarn.lock', 'tsconfig.json']
            }
        }),
```

**Comment by mzgoddard** [comment]
@KnisterPeter 0.6.3 will let webpack finish building. I'll have a targeted fix for this soon.

**Comment by KnisterPeter** [comment]
Awesome. Thanks
