### ISSUE TITLE
Broken with latest webpack 2.1.0-beta23+

### ISSUE THREAD

**Issue by MoOx** [mzgoddard/hard-source-webpack-plugin#34]
When cache is off, build is ok.
When cache is on I am getting random "Module parse failed" "_this.parser.parse is not a function" on a lot of file. Maybe all of them.

Any idea?

```
ModuleParseError: Module parse failed: /Users/moox/Sync/Development/phenomic/lib/redux/createStore/index.js _this.parser.parse is not a function
You may need an appropriate loader to handle this file type.
TypeError: _this.parser.parse is not a function
    at /Users/moox/Sync/Development/phenomic/node_modules/webpack/lib/NormalModule.js:199:17
    at /Users/moox/Sync/Development/phenomic/node_modules/webpack/lib/NormalModule.js:164:10
    at /Users/moox/Sync/Development/phenomic/node_modules/loader-runner/lib/LoaderRunner.js:365:3
    at iterateNormalLoaders (/Users/moox/Sync/Development/phenomic/node_modules/loader-runner/lib/LoaderRunner.js:206:10)
    at /Users/moox/Sync/Development/phenomic/node_modules/loader-runner/lib/LoaderRunner.js:197:4
    at Storage.finished (/Users/moox/Sync/Development/phenomic/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)
    at /Users/moox/Sync/Development/phenomic/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
    at /Users/moox/Sync/Development/phenomic/node_modules/webpack/lib/NormalModule.js:207:34
    at /Users/moox/Sync/Development/phenomic/node_modules/webpack/lib/NormalModule.js:164:10
    at /Users/moox/Sync/Development/phenomic/node_modules/loader-runner/lib/LoaderRunner.js:365:3
    at iterateNormalLoaders (/Users/moox/Sync/Development/phenomic/node_modules/loader-runner/lib/LoaderRunner.js:206:10)
    at /Users/moox/Sync/Development/phenomic/node_modules/loader-runner/lib/LoaderRunner.js:197:4
    at Storage.finished (/Users/moox/Sync/Development/phenomic/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)
    at /Users/moox/Sync/Development/phenomic/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3) 
```

**Comment by MoOx** [comment]
Maybe related to this https://github.com/webpack/webpack/commit/ec262a400728ce5fc9115d4ff5d4f3f7592acf3d

See release notes: https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.23

```
moved parser instancation into NormalModuleFactory

compiler.parser must no longer be used. Use this instead:

compiler.plugin("compilation", function(compilation, params) {
  params.normalModuleFactory.plugin("parser", function(parser, parserOptions) {
    parser.plugin(/* ... */);
  });
});
```
