### ISSUE TITLE
HMR does not work if included in plugins

### ISSUE THREAD

**Issue by bjrnt** [mzgoddard/hard-source-webpack-plugin#39]
Hello,

Awesome project!

I've noticed an issue when using this in combination with `webpack.HotModuleReplacementPlugin`, namely that starting the dev server will succeed once and then fail upon a rebuild (i.e. starting `webpack-dev-server` again) if the HMR plugin was included in `plugins` in the webpack config. However, if this is removed and HMR is enabled through the `--hot` flag, there are no issues.

If it's included as a plugin, the following error is produced on a rebuild:
```
Unhandled rejection TypeError: Cannot read property 'line' of undefined
    at /ProjectDir/node_modules/webpack/lib/Stats.js:224:60
    at Array.map (native)
    at fnModule (/ProjectDir/node_modules/webpack/lib/Stats.js:211:7)
    at Array.map (native)
    at Stats.toJson (/ProjectDir/node_modules/webpack/lib/Stats.js:278:58)
    at Server.<anonymous> (/ProjectDir/node_modules/webpack-dev-server/lib/Server.js:34:39)
    at Compiler.applyPlugins (/ProjectDir/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/ProjectDir/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/ProjectDir/node_modules/webpack/lib/Compiler.js:61:18)
    at MemoryFileSystem.writeFile (/ProjectDir/node_modules/memory-fs/lib/MemoryFileSystem.js:314:9)
    at Compiler.writeFile (/ProjectDir/node_modules/webpack/lib/Compiler.js:295:25)
    at Compiler.<anonymous> (/ProjectDir/node_modules/webpack/lib/Compiler.js:291:13)
    at MemoryFileSystem.(anonymous function) [as mkdirp] (/ProjectDir/node_modules/memory-fs/lib/MemoryFileSystem.js:283:10)
    at Compiler.emitRecords (/ProjectDir/node_modules/webpack/lib/Compiler.js:289:24)
    at Watching.<anonymous> (/ProjectDir/node_modules/webpack/lib/Compiler.js:58:19)
    at /ProjectDir/node_modules/webpack/lib/Compiler.js:275:11
From previous event:
    at Compiler.<anonymous> (/ProjectDir/node_modules/hard-source-webpack-plugin/index.js:710:6)
```

If you need more information about our setup to debug this, please let me know. :)

**Comment by mzgoddard** [comment]
O. K.

So I have a good Idea that https://github.com/webpack/webpack/blob/master/lib/HotModuleReplacementPlugin.js#L230 is the culprit so to speak. The error you are getting is from Stats where it uses the `loc` field on dependencies to be more specific on what it logs. It only does that if `loc` is available. So the problem is `loc` is available and its missing info. Its missing info when HMR is used because the ModuleHotAcceptDependency is using prototype inheritance on that `loc` field but JSON.stringify doesn't stringify prototypical info.

What HardSource will need to do is do a deeper stringify of dependencies so that info is available.

I'm not sure why `--hot` works though. My guess would have to be that a non-HMR cache is being used, so the `ModuleHotAcceptDependency`s do not exist in the cache and so don't have poorly formed `loc` fields to cause errors. (But that would also mean HMR isn't working until you bust the individual modules or the whole cache.)
