### ISSUE TITLE
0.10.0 Error `Cannot read property 'split' of undefined`

### ISSUE THREAD

**Issue by yuqingc** [mzgoddard/hard-source-webpack-plugin#394]
### Expected Behavior

> Please describe what should happen

### Actual Behavior

> Describe what actually happens
```
/home/matt/Projects/freljord/node_modules/hard-source-webpack-plugin/lib/TransformNormalModulePlugin.js:236
        JSON.stringify([resolveKey.context, resolved.resource.split('?')[0]])
                                                              ^
TypeError: Cannot read property 'split' of undefined
    at NormalModule.needRebuild4 [as needRebuild] (/home/matt/Projects/freljord/node_modules/hard-source-webpack-plugin/lib/TransformNormalModulePlugin.js:236:63)
    at Compilation.addModule (/home/matt/Projects/freljord/node_modules/webpack/lib/Compilation.js:308:27)
    at factory.create (/home/matt/Projects/freljord/node_modules/webpack/lib/Compilation.js:567:37)
    at factory (/home/matt/Projects/freljord/node_modules/webpack/lib/NormalModuleFactory.js:405:6)
    at hooks.afterResolve.callAsync (/home/matt/Projects/freljord/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/matt/Projects/freljord/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at resolver (/home/matt/Projects/freljord/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
    at /home/matt/Projects/freljord/node_modules/hard-source-webpack-plugin/lib/TransformNormalModuleFactoryPlugin.js:133:17
    at process.nextTick (/home/matt/Projects/freljord/node_modules/webpack/lib/NormalModuleFactory.js:342:9)
    at process._tickCallback (internal/process/next_tick.js:112:11)
error Command failed with exit code 1.

```

#### Is an error being thrown?

> Include a stack trace if an error is occuring

### Steps to Reproduce

> - Steps to create a minimal reproduction or a link to a repository containing the same
> - Any other information you find helpful reproducing an issue

### Operating System, Node, and NPM dependency versions

```
Ubuntu 18.04
Node 9.8.0

"devDependencies": {
    "add-asset-html-webpack-plugin": "^2.1.3",
    "awesome-typescript-loader": "^5.2.0",
    "clean-webpack-plugin": "^0.1.19",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "file-loader": "^1.1.11",
    "fork-ts-checker-webpack-plugin": "^0.4.2",
    "hard-source-webpack-plugin": "^0.10.0",
    "html-webpack-plugin": "^3.2.0",
    "husky": "1.0.0-rc.9",
    "lint-staged": "^7.2.0",
    "node-sass": "^4.8.3",
    "postcss-loader": "^2.1.5",
    "sass-loader": "^7.0.3",
    "style-loader": "^0.21.0",
    "tsconfig-paths-webpack-plugin": "^3.1.4",
    "tslint": "^5.10.0",
    "typescript": "^2.9.2",
    "uglifyjs-webpack-plugin": "^1.2.7",
    "webpack": "^4.14.0",
    "webpack-cli": "3.0.8",
    "webpack-dev-middleware": "^3.1.2"
  },
  "dependencies": {
    "@types/immutable": "^3.8.7",
    "@types/lodash": "^4.14.110",
    "@types/node": "^10.5.1",
    "@types/prismjs": "^1.9.0",
    "@types/qs": "^6.5.1",
    "@types/react": "^16.4.6",
    "@types/react-copy-to-clipboard": "^4.2.5",
    "@types/react-dom": "^16.0.6",
    "@types/react-redux": "^6.0.3",
    "@types/react-router": "^4.0.27",
    "@types/react-router-dom": "^4.2.7",
    "@types/redux-logger": "^3.0.6",
    "@types/redux-thunk": "^2.1.0",
    "antd": "^3.6.5",
    "autoprefixer": "^8.6.4",
    "axios": "^0.18.0",
    "body-parser": "^1.18.3",
    "express": "^4.16.3",
    "http-proxy-middleware": "^0.18.0",
    "immutable": "^3.8.2",
    "lodash": "^4.17.10",
    "prismjs": "^1.15.0",
    "qs": "^6.5.2",
    "react": "^16.4.1",
    "react-copy-to-clipboard": "^5.0.1",
    "react-dom": "^16.4.1",
    "react-markdown": "^3.3.4",
    "react-redux": "^5.0.7",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"
  }
```

**Comment by yuqingc** [comment]
There is no such issue in v0.9.0

**Comment by blackbird91** [comment]
I have the same problem with v.0.10.0

**Comment by aldarund** [comment]
Same problem too :)

**Comment by mzgoddard** [comment]
I have a fix inbound for this.

**Comment by mzgoddard** [comment]
Fix is merged in. Closing.

Thank you everyone for opening and commenting on this issue.
