### ISSUE TITLE
Trailing commas in functions causing fatal errors

### ISSUE THREAD

**Issue by dextermb** [mzgoddard/hard-source-webpack-plugin#440]
### Expected Behavior

> To run without errors

### Actual Behavior

> Fatal errors because of trailing commas

#### Is an error being thrown?

```
/Users/<snip>/Documents/projects/<snip>/node_modules/hard-source-webpack-plugin/index.js:105
  );
  ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/<snip>/Documents/projects/<snip>/node_modules/next/dist/build/webpack.js:64:55)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

Seems like within the source code there is trailing commas. I've found examples of this on lines:
- [104](https://github.com/mzgoddard/hard-source-webpack-plugin/blob/master/index.js#L104)
- [125](https://github.com/mzgoddard/hard-source-webpack-plugin/blob/master/index.js#L125)

Example using line `125`:
```
    let cachePath = path.resolve(
      process.cwd(),
      this.compilerOutputOptions.path,
      dirName,
    );
```

As you can see, there is a comma after `dirName` which should not be there as it is the last variable within a function.

**Comment by dextermb** [comment]
Seems like I had to bump up my node version. Apparently trailing commas is supported in version 8+

**Comment by ddcovery** [comment]
I have the same problem with Node 6.10.3

Do you know the minimum required node version?

**Comment by dextermb** [comment]
@ddcovery No, I don't `8.12`
