### ISSUE TITLE
ReferenceError: serializer is not defined

### ISSUE THREAD

**Issue by Cyclodex** [mzgoddard/hard-source-webpack-plugin#453]
I have the following issue when using it:

> ReferenceError: serializer is not defined
>     at info (C:\Daten\Reka.RekaNet\node_modules\hard-source-webpack-plugin\lib\CacheSerializerFactory.js:103:22)

It looks like the variable is simply not defined yet, so placing a "var, let or const" seems to fix it...

https://github.com/mzgoddard/hard-source-webpack-plugin/blob/ffe2e641e5a4503b0bd8ed79a82f4716849dba4f/lib/CacheSerializerFactory.js#L103

**Comment by another-guy** [comment]
I am having the same issue, is there a work around that?

**Comment by 8eecf0d2** [comment]
I had the same issue, turned out I had broken links to local packages - `yarn link <package-name>` fixed it.

**Comment by joma74** [comment]
Happend to me too, cause was that i accidentally defined HardSourceWebpackPlugin twice inside the same webpack config.

**Comment by huoyuxin** [comment]
> Happend to me too, cause was that i accidentally defined HardSourceWebpackPlugin twice inside the same webpack config.

defined hard-source and plugin(hard-source-webpack-plugin) at the same time in nuxt.config.js

**Comment by ChenKaiKe** [comment]
> I have the following issue when using it:
> 
> > ReferenceError: serializer is not defined
> > at info (C:...\node_modules\hard-source-webpack-plugin\lib\CacheSerializerFactory.js:103:22)
> 
> It looks like the variable is simply not defined yet, so placing a "var, let or const" seems to fix it...
> 
> https://github.com/mzgoddard/hard-source-webpack-plugin/blob/ffe2e641e5a4503b0bd8ed79a82f4716849dba4f/lib/CacheSerializerFactory.js#L103

so，had fixed it now? I'  placing a "var" before it, it can be normal now.
