### ISSUE TITLE
Error: Can't find options with ident 'vue-loader-options'

### ISSUE THREAD

**Issue by StitchC** [mzgoddard/hard-source-webpack-plugin#534]
### Expected Behavior

webpack compile no error emited

### Actual Behavior

webpack compile emit an error say "Error: Can't find options with ident 'vue-loader-options' "

#### Is an error being thrown?

Error: Can't find options with ident 'vue-loader-options'
    at RuleSet.findOptionsByIdent (/Users/stitch/Documents/work-branch/electron-vue-bootstrap/node_modules/webpack/lib/RuleSet.js:563:10)
    at /Users/stitch/Documents/work-branch/electron-vue-bootstrap/node_modules/hard-source-webpack-plugin/lib/util/serial.js:96:28
    at Array.map (<anonymous>)
    at Object.thaw (/Users/stitch/Documents/work-branch/electron-vue-bootstrap/node_modules/hard-source-webpack-plugin/lib/util/serial.js:69:55)
    at Object.thaw (/Users/stitch/Documents/work-branch/electron-vue-bootstrap/node_modules/hard-source-webpack-plugin/lib/util/serial.js:180:28)
    at contextNormalModuleResolve (/Users/stitch/Documents/work-branch/electron-vue-bootstrap/node_modules/hard-source-webpack-plugin/lib/CacheModuleResolver.js:202:38)
    at /Users/stitch/Documents/work-branch/electron-vue-bootstrap/node_modules/hard-source-webpack-plugin/index.js:342:29
    at Array.forEach (<anonymous>)
    at /Users/stitch/Documents/work-branch/electron-vue-bootstrap/node_modules/hard-source-webpack-plugin/index.js:341:33
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

### Steps to Reproduce

1: webpack config add vue-loader and set options 
              productionMode: !isDev

2: npm run build start compile with webpack

3: error emited of above say

### Operating System, Node, and NPM dependency versions

```
Mac OS 10.15.6
Node 12.16.1

"dependencies": {
    "axios": "^0.19.2",
    "vue": "^2.6.11",
    "vue-router": "^3.3.4",
    "vue-class-component": "^7.2.5",
    "vue-property-decorator": "^9.0.0",
    "vuex": "^3.5.1"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^3.7.1",
    "@typescript-eslint/parser": "^3.7.1",
    "babel-loader": "^8.1.0",
    "cfonts": "^2.8.6",
    "chalk": "^4.1.0",
    "copy-webpack-plugin": "^6.0.3",
    "cross-env": "^7.0.2",
    "css-loader": "^4.2.0",
    "del": "^5.1.0",
    "electron": "^7.3.2",
    "electron-builder": "^22.8.0",
    "eslint": "^7.5.0",
    "eslint-config-airbnb-base": "^14.2.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-vue": "^6.2.2",
    "fork-ts-checker-notifier-webpack-plugin": "^3.0.0",
    "fork-ts-checker-webpack-plugin": "^5.0.14",
    "happypack": "^5.0.1",
    "hard-source-webpack-plugin": "^0.13.1",
    "html-webpack-plugin": "^4.3.0",
    "husky": "^4.2.5",
    "mini-css-extract-plugin": "^0.9.0",
    "native-ext-loader": "^2.3.0",
    "node-loader": "^1.0.1",
    "optimize-css-assets-webpack-plugin": "^5.0.3",
    "sass": "^1.26.10",
    "sass-loader": "^9.0.3",
    "style-loader": "^1.2.1",
    "terser-webpack-plugin": "^3.0.8",
    "ts-loader": "^8.0.2",
    "typescript": "^3.9.7",
    "url-loader": "^4.1.0",
    "vue-loader": "^15.9.3",
    "vue-template-compiler": "^2.6.11",
    "webpack": "^4.44.1",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0",
    "webpack-merge": "^5.1.1"
  }
```

**Comment by StitchC** [comment]
ah i solve this problem, because i custom define the cache directory use options "configHash" eg.
`
new HardSourceWebpackPlugin({
      configHash() {
        return process.env.NODE_ENV
      }
}),
`
and i use webpack to pack my electron application renderer and main process, the both process webpack config i both use hard-source-webpack-plugin , so i think the cache content will cause overwrite when webpack compiling, when i add a prefix into the "configHash" return value, eg.

`
new HardSourceWebpackPlugin({
      configHash() {
        return processType + process.env.NODE_ENV
      }
}),
`

the error no more emit
