### ISSUE TITLE
Compiler Stats - errors and warnings - dep.loc.start undefined.

### ISSUE THREAD

**Issue by alexanderhansensc** [mzgoddard/hard-source-webpack-plugin#54]
I get this error from HtmlWebpackPlugin, but I looked through HtmlWebpackPlugin doesn't seem like any of the options avoid this line because it happens within the emit step.

Error from second compilation

```
Unhandled rejection TypeError: Cannot read property 'line' of undefined
    at ./node_modules/webpack/lib/Stats.js:224:60
    at Array.map (native)
    at fnModule (./node_modules/webpack/lib/Stats.js:211:7)
    at Array.map (native)
    at Stats.toJson (./node_modules/webpack/lib/Stats.js:278:58)
    at Compiler.<anonymous> (./node_modules/html-webpack-plugin/index.js:68:59)
    at Compiler.applyPluginsAsync (./node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.emitAssets (./node_modules/webpack/lib/Compiler.js:226:7)
    at Watching.<anonymous> (./node_modules/webpack/lib/Compiler.js:54:18)
    at ./node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (./node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (./node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.next (./node_modules/tapable/lib/Tapable.js:69:14)
    at ./node_modules/hard-source-webpack-plugin/index.js:712:7
From previous event:
    at Compiler.<anonymous> (./node_modules/hard-source-webpack-plugin/index.js:710:6)
    at Compiler.applyPluginsAsync (./node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (./node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (./node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.applyPluginsAsync (./node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (./node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.applyPluginsAsync (./node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (./node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.next (./node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (./node_modules/extract-text-webpack-plugin/index.js:309:4)
    at Compilation.applyPluginsAsync (./node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (./node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.next (./node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (./node_modules/extract-text-webpack-plugin/index.js:285:5)
    at ./node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (./node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (./node_modules/async/lib/async.js:209:22)
    at ExtractTextPlugin.<anonymous> (./node_modules/extract-text-webpack-plugin/index.js:237:10)
    at Compilation.applyPluginsAsync (./node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.seal (./node_modules/webpack/lib/Compilation.js:525:7)
    at Compiler.<anonymous> (./node_modules/webpack/lib/Compiler.js:397:15)
    at ./node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (./node_modules/webpack/lib/Compilation.js:445:10)
    at ./node_modules/webpack/lib/Compilation.js:417:12
    at ./node_modules/webpack/lib/Compilation.js:332:10
```

Versions

```
"hard-source-webpack-plugin": "0.0.42"
"html-webpack-plugin": "2.22.0",
"webpack": "1.13.2"
```

The error actually  comes from `webpack/lib/Stats.js` because `options.reasons` defaults to true

```
    var showReasons = d(options.reasons, !forToString);
```

I think these are stats of errors and warnings. Eg. `compilation.errors` `compilation.warnings`

Webpack's failing block

```
    obj.reasons = module.reasons.filter(function(reason) {
        return reason.dependency && reason.module;
    }).map(function(reason) {
        var obj = {
            moduleId: reason.module.id,
            moduleIdentifier: reason.module.identifier(),
            module: reason.module.readableIdentifier(requestShortener),
            moduleName: reason.module.readableIdentifier(requestShortener),
            type: reason.dependency.type,
            userRequest: reason.dependency.userRequest
        };
        var dep = reason.dependency;
        if(dep.templateModules) obj.templateModules = dep.templateModules.map(function(module) {
            return module.id;
        });
        if(typeof dep.loc === "object") obj.loc = dep.loc.start.line + ":" + dep.loc.start.column + "-" +
            (dep.loc.start.line !== dep.loc.end.line ? dep.loc.end.line + ":" : "") + dep.loc.end.column;
        return obj;
    }).sort(function(a, b) {
        return a.moduleId - b.moduleId;
    });
```

Essentially, dep.loc exists, but doesn't have the start/end line/column properties. To avoid this we either need to cache the locations or they should be removed to avoid this. Below is what the compilation object looks like on the second run. If instead `loc` was undefined or `loc.start` and `loc.end` were undefined it wouldn't fail.

```
compilation = {
    errors: [{
        loc: {
            start: undefined,
            end: undefined,
        },
    }],
    warnings: [{
        loc: {
            start: undefined,
            end: undefined,
        }
    }]
}
```

I only get into this error due to HtmlWebpackPlugin, but I don't think it's avoidable by configuration because it happens right after the emit step (see below). Looking through the previous issues, I know some people have been using this plugin successfully with it. Perhaps this is by just not having errors or warnings in the compilation object?

```
  compiler.plugin('emit', function (compilation, callback) {
    var applyPluginsAsyncWaterfall = Promise.promisify(compilation.applyPluginsAsyncWaterfall, {context: compilation});
    // Get all chunks
    var chunks = self.filterChunks(compilation.getStats().toJson(), self.options.chunks, self.options.excludeChunks);
```

I'd be happy to fix it if someone could point me in the right direction. My guess was that the best way would just to be to modify `serializeDependencies` in `https://github.com/mzgoddard/hard-source-webpack-plugin/blob/1f5618cf358d274e9777b67ea5dba97db0989284/index.js`, but I wanted to confirm that.

In case anyone else is running into this, my workaround was the following. Obviously this could indirectly create some other problems for a plugin that actually needs the stats and doesn't specify it, but this worked for me.

```
var WebpackStats = require('webpack/lib/Stats');
  var wsToJson = WebpackStats.prototype.toJson;
  WebpackStats.prototype.toJson = function toJson() {
    var args = [].slice.call(arguments);
    if (!args.length) {
      args.push({ reasons: false });
    }
    return wsToJson.apply(this, args);
  };
```

Thanks a lot by the way, I think this plugin is going to make us a lot more productive.

**Comment by mzgoddard** [comment]
Thank you @alexanderhansensc for this really detailed issue. I think this bug is already covered in `0.0.43` through https://github.com/mzgoddard/hard-source-webpack-plugin/pull/41. You might some other detail in https://github.com/mzgoddard/hard-source-webpack-plugin/issues/39#issuecomment-251758716 as well.

The short version is HMR and other plugins may build their `.loc` value as a prototype chain and `JSON.stringify` doesn't by default climb prototype chains. So `0.0.43` specifically flattens the `loc` object that it freezes so these values aren't left out. This should also leave alone any case where `.loc` is undefined which as you already pointed out is fine and goes around this issue.

Hope this helps. Let me know if there is something more still going on.

**Comment by alexanderhansensc** [comment]
Sounds good, I'll give it a try. Thanks.
