### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by xumqfaith** [mzgoddard/hard-source-webpack-plugin#541]
[hard-source:core] HardSourceWebpackPlugin is using 429 MB of disk space.
 ERROR  TypeError: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined
    at Object.exports.call (E:\webpack4\node_modules\hard-source-webpack-plugin\lib\util\plugin-compat.js:171:17)
    at Proxy.run (E:\webpack4\node_modules\hard-source-webpack-plugin\lib\SystemArchetype.js:184:20)
    at E:\webpack4\node_modules\speed-measure-webpack-plugin\WrappedPlugin\index.js:52:19
    at _next1 (eval at create (E:\webpack4\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:45:1)
    at eval (eval at create (E:\webpack4\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:73:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-element-admin@4.4.0 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-element-admin@4.4.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-12-31T08_49_22_841Z-debug.log

plugins:[
new HardSourceWebpackPlugin()
]

  "dependencies": {
    "@packy-tang/vue-tinymce": "^1.1.0",
    "axios": "0.18.1",
    "clipboard": "2.0.4",
    "codemirror": "5.45.0",
    "core-js": "3.6.5",
    "driver.js": "0.9.5",
    "dropzone": "5.5.1",
    "echarts": "4.2.1",
    "element-ui": "2.13.2",
    "file-saver": "2.0.1",
    "fuse.js": "3.4.4",
    "jquery": "^2.2.0",
    "js-cookie": "^2.2.0",
    "js-md5": "^0.7.3",
    "jsonlint": "1.6.3",
    "jszip": "3.2.1",
    "normalize.css": "7.0.0",
    "nprogress": "0.2.0",
    "path-to-regexp": "2.4.0",
    "screenfull": "4.2.0",
    "script-loader": "0.7.2",
    "sortablejs": "1.8.4",
    "tui-editor": "1.3.3",
    "v-charts": "^1.19.0",
    "vue": "2.6.10",
    "vue-count-to": "1.0.13",
    "vue-router": "3.0.2",
    "vue-splitpane": "1.0.4",
    "vuedraggable": "2.20.0",
    "vuex": "3.1.0",
    "xlsx": "0.14.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "4.4.4",
    "@vue/cli-plugin-eslint": "4.4.4",
    "@vue/cli-plugin-unit-jest": "4.4.4",
    "@vue/cli-service": "4.4.4",
    "@vue/test-utils": "1.0.0-beta.29",
    "autoprefixer": "9.5.1",
    "babel-eslint": "10.1.0",
    "babel-jest": "23.6.0",
    "babel-plugin-dynamic-import-node": "2.3.3",
    "chalk": "2.4.2",
    "chokidar": "2.1.5",
    "connect": "3.6.6",
    "eslint": "6.7.2",
    "eslint-plugin-vue": "6.2.2",
    "hard-source-webpack-plugin": "^0.13.1",
    "html-webpack-plugin": "3.2.0",
    "husky": "1.3.1",
    "lint-staged": "8.1.5",
    "mockjs": "1.0.1-beta3",
    "plop": "2.3.0",
    "runjs": "4.3.2",
    "sass": "1.26.2",
    "sass-loader": "8.0.2",
    "script-ext-html-webpack-plugin": "2.1.3",
    "serve-static": "1.13.2",
    "speed-measure-webpack-plugin": "^1.3.3",
    "svg-sprite-loader": "4.1.3",
    "svgo": "1.2.0",
    "uglifyjs-webpack-plugin": "^2.2.0"
  },

**Comment by banchichen** [comment]
same issue, cannot be used with speed-measure-webpack-plugin

https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/21
