### ISSUE TITLE
Failed to read cache during the second build

### ISSUE THREAD

**Issue by careyke** [mzgoddard/hard-source-webpack-plugin#544]
### Expected Behavior
The second build should read from the cache

### Actual Behavior
Failed to read cache during the second build
```
[hardsource:b4f88118] Using 354 MB of disk space.
[hardsource:b4f88118] Tracking node dependencies with: package-lock.json.
[hardsource:b4f88118] Reading from cache b4f88118...
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
    at new NodeError (node:internal/errors:329:5)
    at Hash.update (node:internal/crypto/hash:105:11)
    at BulkUpdateDecorator.update (/Users/herman/work/projects/fiber-project-app/web/node_modules/webpack/lib/util/createHash.js:61:14)
    at CssDependency.updateHash (/Users/herman/work/projects/fiber-project-app/web/node_modules/hard-source-webpack-plugin/lib/SupportMiniCssExtractPlugin.js:7:10)
    at NormalModule.updateHash (/Users/herman/work/projects/fiber-project-app/web/node_modules/webpack/lib/DependenciesBlock.js:80:44)
    at NormalModule.updateHash (/Users/herman/work/projects/fiber-project-app/web/node_modules/webpack/lib/Module.js:313:9)
    at NormalModule.updateHash (/Users/herman/work/projects/fiber-project-app/web/node_modules/webpack/lib/NormalModule.js:578:9)
    at Compilation.createHash (/Users/herman/work/projects/fiber-project-app/web/node_modules/webpack/lib/Compilation.js:1940:11)
    at /Users/herman/work/projects/fiber-project-app/web/node_modules/webpack/lib/Compilation.js:1386:9
    at eval (eval at create (/Users/herman/work/projects/fiber-project-app/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Operating System, Node, and NPM dependency versions

```
Mac OS 10.15.3
Node 15.10.0

"devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-transform-runtime": "^7.12.10",
    "@babel/preset-env": "^7.12.11",
    "@babel/preset-react": "^7.12.10",
    "@babel/preset-typescript": "^7.12.7",
    "@babel/runtime": "^7.12.5",
    "@typescript-eslint/eslint-plugin": "^4.14.1",
    "@typescript-eslint/parser": "^4.14.1",
    "autoprefixer": "^10.2.4",
    "babel-loader": "^8.2.2",
    "babel-plugin-import": "^1.13.3",
    "cache-loader": "^4.1.0",
    "clean-webpack-plugin": "^3.0.0",
    "core-js": "^3.8.3",
    "cross-env": "^7.0.3",
    "css-loader": "^5.0.1",
    "eslint": "^7.19.0",
    "eslint-config-prettier": "^7.2.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-react": "^7.22.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "eslint-webpack-plugin": "^2.4.3",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "glob": "^7.1.6",
    "hard-source-webpack-plugin": "^0.13.1",
    "html-webpack-plugin": "^4.5.1",
    "husky": "^4.3.8",
    "less": "^4.1.1",
    "less-loader": "^7.3.0",
    "lint-staged": "^10.5.3",
    "mini-css-extract-plugin": "^1.3.5",
    "optimize-css-assets-webpack-plugin": "^5.0.4",
    "path": "^0.12.7",
    "path-to-regexp": "^1.8.0",
    "postcss": "^8.2.4",
    "postcss-loader": "^4.2.0",
    "prettier": "^2.2.1",
    "purgecss-webpack-plugin": "^2.1.0",
    "style-loader": "^2.0.0",
    "terser-webpack-plugin": "^4.2.0",
    "typescript": "^4.1.5",
    "url-loader": "^4.1.1",
    "webpack": "^4.46.0",
    "webpack-bundle-analyzer": "^4.4.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.2",
    "webpack-merge": "^5.7.3"
  },
"dependencies": {
  "@types/classnames": "^2.2.11",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-router-dom": "^5.1.7",
    "antd": "^4.11.2",
    "axios": "^0.21.1",
    "classnames": "^2.2.6",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-router-dom": "^5.2.0"
}
```

**Comment by nicholasxjy** [comment]
https://github.com/mzgoddard/hard-source-webpack-plugin#excludemoduleplugin

**Comment by careyke** [comment]
> https://github.com/mzgoddard/hard-source-webpack-plugin#excludemoduleplugin

Thank you ! i will try it

**Comment by wujiantao123** [comment]
I tried adding ExcludeModulePlugin to ignore, but I still get the same error
![image](https://user-images.githubusercontent.com/30134626/112828277-1678c200-90c2-11eb-84fa-ad8bf1019470.png)
