### ISSUE TITLE
Doesn't work w/ webpack 2.2 rc.0

### ISSUE THREAD

**Issue by aaronjensen** [mzgoddard/hard-source-webpack-plugin#77]
```
/Users/aaronjensen/Source/app/node_modules/hard-source-webpack-plugin/index.js:939
          return stat(resource)
                 ^

TypeError: stat is not a function
    at /Users/aaronjensen/Source/app/node_modules/hard-source-webpack-plugin/index.js:939:18
    at /Users/aaronjensen/Source/app/node_modules/hard-source-webpack-plugin/index.js:949:12
    at /Users/aaronjensen/Source/app/node_modules/webpack/lib/NormalModuleFactory.js:59:4
    at /Users/aaronjensen/Source/app/node_modules/webpack/lib/NormalModuleFactory.js:234:3
    at /Users/aaronjensen/Source/app/node_modules/tapable/lib/Tapable.js:168:11
    at NormalModuleFactory.<anonymous> (/Users/aaronjensen/Source/app/node_modules/hard-source-webpack-plugin/index.js:1043:39)
    at /Users/aaronjensen/Source/app/node_modules/tapable/lib/Tapable.js:170:14
    at NormalModuleFactory.<anonymous> (/Users/aaronjensen/Source/app/node_modules/webpack/lib/NormalModuleReplacementPlugin.js:26:11)
    at /Users/aaronjensen/Source/app/node_modules/tapable/lib/Tapable.js:170:14
    at NormalModuleFactory.<anonymous> (/Users/aaronjensen/Source/app/node_modules/webpack/lib/NormalModuleReplacementPlugin.js:26:11)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/aaronjensen/Source/app/node_modules/tapable/lib/Tapable.js:172:13)
    at NormalModuleFactory.create (/Users/aaronjensen/Source/app/node_modules/webpack/lib/NormalModuleFactory.js:218:8)
    at iteratorFactory (/Users/aaronjensen/Source/app/node_modules/webpack/lib/Compilation.js:213:11)
    at /Users/aaronjensen/Source/app/node_modules/async/dist/async.js:3025:16
    at eachOfArrayLike (/Users/aaronjensen/Source/app/node_modules/async/dist/async.js:941:9)
    at eachOf (/Users/aaronjensen/Source/app/node_modules/async/dist/async.js:991:5)
```

**Comment by mzgoddard** [comment]
Thanks for the issue @aaronjensen. I have compatibility changes in `0.3.4` now.
