### ISSUE TITLE
TypeError: Cannot read property 'dependencies' of null

### ISSUE THREAD

**Issue by thangngoc89** [mzgoddard/hard-source-webpack-plugin#8]
I get this error when I forgot to clean the cache (eg: Checkout back to a old commit)

```
/home/khoa/web/nkpb/node_modules/hard-source-webpack-plugin/index.js:351
            block.dependencies.forEach(callback);
                 ^

TypeError: Cannot read property 'dependencies' of null
    at walkDependencyBlock (/home/khoa/web/nkpb/node_modules/hard-source-webpack-plugin/index.js:351:18)
    at /home/khoa/web/nkpb/node_modules/hard-source-webpack-plugin/index.js:368:13
    at Array.forEach (native)
    at /home/khoa/web/nkpb/node_modules/hard-source-webpack-plugin/index.js:360:36
    at FSReqWrap.oncomplete (fs.js:123:15)
```

Webpack config: https://github.com/thangngoc89/electron-react-app/blob/cf73f6e6e3da84757898c01e38d25a5ce573a036/webpack.config.js

**Comment by trotzig** [comment]
I'm seeing something similar as well. This error will happen any time I delete a whole folder:

```
Unhandled rejection TypeError: Cannot read property 'dependencies' of null
    at walkDependencyBlock (/Users/henrictrotzig/brigade/node_modules/hard-source-webpack-plugin/index.js:233:16)
    at /Users/henrictrotzig/brigade/node_modules/hard-source-webpack-plugin/index.js:250:11
    at Array.forEach (native)
    at /Users/henrictrotzig/brigade/node_modules/hard-source-webpack-plugin/index.js:242:34
    at tryCatcher (/Users/henrictrotzig/brigade/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/henrictrotzig/brigade/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/henrictrotzig/brigade/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/henrictrotzig/brigade/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/henrictrotzig/brigade/node_modules/bluebird/js/release/promise.js:680:18)
    at Async._drainQueue (/Users/henrictrotzig/brigade/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/Users/henrictrotzig/brigade/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/henrictrotzig/brigade/node_modules/bluebird/js/release/async.js:16:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

That was after deleteing a folder using `git rm -r app/assets/components/SidebarNavigation`.

**Comment by trotzig** [comment]
@thangngoc89 can you check if you get the same error if you remove a folder? If so maybe you can change the issue title to something that better reflects what is causing the error.

**Comment by mzgoddard** [comment]
The problem here is probably pretty simple. The block of code happening is invalidating modules because files were moved or deleted. Looks like that section of code is missing a really simple check to make sure its considering a module. This is probably happening because two files moved at the same time, the first invalidating related modules, the second choking up on the `null`ed modules.
