### ISSUE TITLE
TypeError: Cannot read property 'identifier' of undefined

### ISSUE THREAD

**Issue by legomushroom** [mzgoddard/hard-source-webpack-plugin#91]
Having this error after moving to `webpack2`.

Entire log:
```shell
/Applications/MAMP/htdocs/Glimpse.Client/node_modules/hard-source-webpack-plugin/lib/hard-context-module-factory.js:76
    var identifier = identifierPrefix + module.identifier();
                                              ^

TypeError: Cannot read property 'identifier' of undefined
    at /Applications/MAMP/htdocs/Glimpse.Client/node_modules/hard-source-webpack-plugin/lib/hard-context-module-factory.js:76:47
    at /Applications/MAMP/htdocs/Glimpse.Client/node_modules/webpack/lib/ContextModuleFactory.js:37:22
    at /Applications/MAMP/htdocs/Glimpse.Client/node_modules/webpack/node_modules/tapable/lib/Tapable.js:204:11
    at ContextModuleFactory.cmf.plugin (/Applications/MAMP/htdocs/Glimpse.Client/node_modules/webpack/lib/IgnorePlugin.js:30:13)
    at ContextModuleFactory.applyPluginsAsyncWaterfall (/Applications/MAMP/htdocs/Glimpse.Client/node_modules/webpack/node_modules/tapable/lib/Tapable.js:208:13)
    at ContextModuleFactory.create (/Applications/MAMP/htdocs/Glimpse.Client/node_modules/webpack/lib/ContextModuleFactory.js:26:7)
    at next (/Applications/MAMP/htdocs/Glimpse.Client/node_modules/hard-source-webpack-plugin/lib/hard-context-module-factory.js:59:15)
    at HardContextModuleFactory.create (/Applications/MAMP/htdocs/Glimpse.Client/node_modules/hard-source-webpack-plugin/lib/hard-context-module-factory.js:66:3)
    at iteratorFactory (/Applications/MAMP/htdocs/Glimpse.Client/node_modules/webpack/lib/Compilation.js:209:12)
    at /Applications/MAMP/htdocs/Glimpse.Client/node_modules/webpack/node_modules/async/dist/async.js:3025:16
    at eachOfArrayLike (/Applications/MAMP/htdocs/Glimpse.Client/node_modules/webpack/node_modules/async/dist/async.js:941:9)
    at eachOf (/Applications/MAMP/htdocs/Glimpse.Client/node_modules/webpack/node_modules/async/dist/async.js:991:5)
    at Object.eachLimit (/Applications/MAMP/htdocs/Glimpse.Client/node_modules/webpack/node_modules/async/dist/async.js:3089:3)
    at Compilation.addModuleDependencies (/Applications/MAMP/htdocs/Glimpse.Client/node_modules/webpack/lib/Compilation.js:190:9)
    at Compilation.processModuleDependencies (/Applications/MAMP/htdocs/Glimpse.Client/node_modules/webpack/lib/Compilation.js:175:8)
    at _this.buildModule.err (/Applications/MAMP/htdocs/Glimpse.Client/node_modules/webpack/lib/Compilation.js:315:13)
```

This is the plugin's config:

```javascript
// ...
new HardSourcePlugin({
   cacheDirectory: `${dirname}.cache/[confighash]`,
   recordsPath: `${dirname}.cache/[confighash]/records.json`,
   configHash: function configHash(webpackConfig) {
       return require('node-object-hash')().hash(webpackConfig);
   },
   environmentHash: {
       root: `${process.cwd()}/`,
       directories: ['node_modules'],
       files: ['package.json']
   }
}),
// ...
```

Will appreciate any help!

**Comment by mzgoddard** [comment]
@legomushroom I was looking at this earlier to start mulling over what is going on. This is frankly super weird. This error implies that the function erroring is getting no values when its called. No error or module. If the wrapped factory found no module, I think it is supposed to give an error which the function will forward.

Is there any more of your config you can share?

**Comment by legomushroom** [comment]
Hi @mzgoddard!

Thanks for the response.
I figured out the exact problem. I was using `webpack.IgnorePlugin` (for [`moment.js` issue](https://github.com/moment/moment/issues/2373)) like this:
```
new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
```
This caused the error. Yep, both `error` and `module` were `undefined`. Works like a charm after removing the `IgnorePlugin`.

**Comment by mzgoddard** [comment]
Awesome. Thanks for letting me know that'll really help me add units and
support for Ignore.
